website/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views as my_views

app_name = "woltshare"

urlpatterns = [
    path("", my_views.HomeView.as_view()),
    # path("buy/", my_views.BuyView.as_view()),
    # path("products/<slug:food_id>", my_views.BuyProductView.as_view()),
    path(
        "sell/",
        my_views.ProductCreateFormView.as_view(),
        # name="product-add-form",
        name="product_add",
    ),
    # path("product/add/", my_views.product_add, name="product_add"),
    path("done/", my_views.DoneView.as_view()),
    path("product/", my_views.ProductsView.as_view()),
    path("product/<int:pk>/", my_views.ProductView.as_view(), name="product-update"),
    path("purchase/<int:pk>/", my_views.purchase_view),
    path(
        "product/<int:pk>/delete/",
        my_views.ProductDeleteView.as_view(),
        name="product-delete",
    ),
    # Users
    path(
        "login/",
        my_views.LoginView.as_view(),
        name="account_login",
    ),
    path(
        "accounts/profile/",
        my_views.CustomUserOwnView.as_view(),
        name="profile",
    ),
    path(
        "accounts/profile/<int:pk>",
        my_views.CustomUserView.as_view(),
        name="profile",
    ),
]

woltshare/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings #add this
from django.conf.urls.static import static #add this

urlpatterns = [
    path("", include("website.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
import datetime

from django.conf import settings
from django.contrib.auth.models import AbstractUser, User
from django.db import models

from django.contrib.postgres.fields import ArrayField


class CustomUser(AbstractUser):
    email = models.EmailField("email address", unique=True)
    username = models.CharField("username", max_length=30, blank=True, unique=True)
    name = models.CharField("Name Surname", max_length=256)
    phone = models.CharField("Phone number", max_length=256, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)
    lon = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)
    address = models.CharField("address", max_length=256)


FOOD_TYPE_CHOICES = (
    ("PACK", "Packaged food"),
    ("COOK", "Cooked food"),
    ("VEGE", "Vegetables"),
    ("FRUT", "Fruits"),
)


class Product(models.Model):
    title = models.CharField("Title", max_length=512)
    seller = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="%(class)s_seller"
    )
    quantity = models.IntegerField("Quantity")
    price_per_quant = models.FloatField("Price per quantity")
    description = models.CharField("Description", max_length=512)
    # ingredients = models.CharField("Ingredients", max_length=512)
    ingredients = ArrayField(models.CharField("Ingredients", max_length=512))
    food_type = models.CharField(
        max_length=4, choices=FOOD_TYPE_CHOICES, default="PACK"
    )
    packaging = models.BooleanField("Does it have packaging", default="False")
    image = models.ImageField("Image", upload_to="products")
    date = models.DateField("Date", default=datetime.date.today)


class Transaction(models.Model):
    seller = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="%(class)s_seller"
    )
    buyer = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="%(class)s_buyer"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="%(class)s_product"
    )
    price = models.IntegerField("Pice")
    quantity = models.IntegerField("Quantity")

website/forms.py
from django import forms

from .models import Product


class SellForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def add_product(self):
        # send email using the self.cleaned_data dictionary
        print("add_product", self.cleaned_data)


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # for visible in self.visible_fields():
        #     visible.label.widget.attrs['class'] = 'form-control-label'

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        # visible.label.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = [
            "seller",
            "quantity",
            "price_per_quant",
            "description",
            "food_type",
            "packaging",
            "date",
        ]

website/views.py
import os

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    FormView,
    RedirectView,
    TemplateView,
    UpdateView,
    View,
)
from django.views.generic.detail import DetailView

from . import api_set_order
from .api_get_price import DelFeeReq_strg, get_fee
from .forms import ProductForm, SellForm
from .models import CustomUser, Product


class HomeView(TemplateView):
    template_name = "home.html"


# class PurchaseView(RedirectView):
#     permanent = False
#     query_string = True
#     pattern_name = 'article-detail'

#     def get_redirect_url(self, *args, **kwargs):
#         article = get_object_or_404(Article, pk=kwargs['pk'])
#         article.update_counter()
#         return super().get_redirect_url(*args, **kwargs)


class LoginView(TemplateView):
    template_name = "login.html"


def purchase_view(request, pk):
    buyer = request.user

    buyer = api_set_order.User(
        buyer.name,
        buyer.address,
        buyer.phone,
        buyer.email,
    )

    product = Product.objects.get(id=pk)
    seller = product.seller
    seller = api_set_order.User(
        seller.name,
        seller.address,
        seller.phone,
        seller.email,
    )
    order = api_set_order.Order(seller, buyer, 2579)
    order_strg = api_set_order.makeOrderStrg(order)
    url = api_set_order.make_order(order_strg)

    return redirect(url)


class ProductsView(TemplateView):
    template_name = "buy.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # All products
        products_pack = Product.objects.filter(food_type="PACK")  # .order_by("date")
        products_cook = Product.objects.filter(food_type="COOK")  # .order_by("date")
        context["products_pack"] = products_pack
        context["products_cook"] = products_cook
        return context


class ProductView(TemplateView):
    template_name = "product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # All products
        pk = self.kwargs["pk"]
        product = Product.objects.get(id=pk)
        shipping_cost = self._get_shipping_fee(product.seller, self.request.user)
        context["product"] = product
        context["shipping_cost"] = shipping_cost / 100
        return context

    def _get_shipping_fee(self, seller: CustomUser, buyer: CustomUser):
        start = seller.address
        end = buyer.address
        myStrgReq = DelFeeReq_strg(start, end)
        return get_fee(myStrgReq)


class ProductCreateFormView(View):
    def get(self, request):
        return render(request, "post_form.html")

    def post(self, request):
        return redirect("/product/")


class ProductDeleteView(DeleteView):
    product = Product


class DoneView(TemplateView):
    template_name = "done.html"


class CustomUserView(TemplateView):
    template_name = "profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # All products
        pk = self.kwargs["pk"]
        user = CustomUser.objects.get(id=pk)
        context["user"] = user
        return context


class CustomUserOwnView(TemplateView):
    template_name = "profile.html"


#     def form_valid(self, form):
#         # This method is called when valid form data has been POSTed.
#         # It should return an HttpResponse.
#         form.add_product()
#         return super().form_valid(form)


def product_add(request):
    data = {}
    if request.method == "POST":
        data = request.POST.dict()

        print("hee", CustomUser.objects.all())
        print("hoo", CustomUser.objects.all()[0])
        seller = CustomUser.objects.all()[0]

        quantity = data["quantity"]
        price_per_quant = data["price_per_quant"]
        description = data["description"]
        food_type = data["food_type"]
        if "packaging" in data:
            packaging = data["packaging"] == "on"
        else:
            packaging = False

        # image = data["image"]

        print("pack", packaging)

        # # rules
        # if "rules" not in data:
        #     # reload? not let forward
        #     return render(
        #         request,
        #         "post_form.html",
        #         {"error": "Accept terms of condition, please!"},
        #     )

        print("PRODS", Product.objects.all().values())
        product.save()

    return render(request, "success.html", {"product": data})

website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>WoltShare</title>
    <meta
      content="WoltShare for sharing your favourite food with your community"
      name="description"
    />
    <meta
      content="food, wolt, sharing, caring, economy, waste"
      name="keywords"
    />
    <link href="https://static.wolt.com/favicon.ico" rel="icon" />
    <link href="https://static.wolt.com/favicon.ico" rel="apple-touch-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />

    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />


    <script>
      function readURL(input) {
        if (input.files && input.files[0]) {

          var reader = new FileReader();

          reader.onload = function(e) {
            $('.image-upload-wrap').hide();

            $('.file-upload-image').attr('src', e.target.result);
            $('.file-upload-content').show();

            $('.image-title').html(input.files[0].name);
          };

          reader.readAsDataURL(input.files[0]);

        } else {
          removeUpload();
        }
      }

      function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
      }
      $('.image-upload-wrap').bind('dragover', function () {
          $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
          $('.image-upload-wrap').removeClass('image-dropping');
      });
    </script>



  </head>

  <body>
    <header id="header" class="header fixed-top d-flex align-items-center">
      <div class="container d-flex align-items-center justify-content-between">
        <a
          href="/"
          class="logo d-flex align-items-center me-auto me-lg-0"
        >
          <img src="{% static 'images/logo.png' %}" alt="wolt logo" />
        </a>
        <nav class="navbar">
          {% if not user.is_authenticated %}
          <a
            class="navbar-toggler-right"
            href="/accounts/login"
            style="margin-left: 40px"
            class="glightbox"
            >Log in</a
          >
          <a class="btn-11" href="/accounts/login">Sign up</a>
          <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
          <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
          {% else %}
          <a class="btn-11" href="/accounts/profile">My Profile</a>
          {% endif %}
        </nav>
      </div>
    </header>


    {% block content %}{% endblock %}

    <footer id="footer" class="footer">
      <div class="container">
        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <div>
            <img
              src="{% static 'images/woltW.png' %}"
              class="w-50 logo-footer"
            />
          </div>
        </div>
        <div class="row gy-3">
          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Follow Us</h4>
            <div class="social-links d-flex">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 footer-links d-flex">
            <div>
              <h4>Let's do this together</h4>
              <p>
                How does WoltShare work <br />
                Wolt Drive <br />
                Join us <br />
              </p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex">
            <div>
              <h4>Company</h4>
              <p>
                About us <br />
                Responsability <br />
                Security <br />
              </p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 footer-links d-flex">
            <div>
              <h4>Useful links</h4>
              <p>
                Support <br />
                Media <br />
                Contact <br />
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>WoltShare</span></strong
          >. All Rights Reserved
        </div>
      </div>
    </footer>
    <a
      href="#"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <div id="preloader"></div>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

website/templates/buy.html
{% extends 'base.html' %}
{% load static %}

{% comment %}

{% for product in products %}
    <a href="/product/{{product.id}}/">Link product {{product.id}}</a> <br/>
    {{product.id}}<br/>
    {{product.seller}}<br/>
    {{product.quantity}}<br/>
    {{product.price_per_quant}}<br/>
    {{product.description}}<br/>
    {{product.type}}<br/>
    {{product.packaging}}<br/>
    ===<br/>
{% endfor %}

{% endcomment %}


{% block content %}
  <main id="main">

	    <section id="sell" class="sell">
      <div class="container" data-aos="fade-up">

        <div class="section-header" id="pages">
          <h2>SEE WHAT SHARERS ARE SHARING</h2>
          <p>Check it <span>out</span></p>
        </div>

        <ul class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="200">

          <li class="nav-item">
            <a class="nav-link active show" data-bs-toggle="tab" data-bs-target="#cooked">
              <h4>Cooked food</h4>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" data-bs-target="#ingredients">
              <h4>Ingredients</h4>
            </a><!-- End tab nav item -->
        </ul>

        <div class="tab-content" data-aos="fade-up" data-aos-delay="300">

          <div class="tab-pane fade active show" id="cooked">

            <div class="tab-header text-center">
              <p>What Sharers</p>
              <h3>have cooked</h3>
            </div>

		<div class="row gy-5">
			<div class="row gy-5">

                {% for product in products_cook %}



				<div class="col-lg-4 sell-item">
					<a href="/product/{{product.id}}"><img src="/media/{{product.image }}" class="sell-img img-fluid" alt=""></a>
					<h4>{{product.title}}</h4>
					<p class="ingr">
						{{product.ingredients|slice:":40"}}
					</p>
					<p class="price">
						€{{product.price_per_quant}}
					</p>
				</div>

                {% endfor %}
			  </div>
			  </div>
          </div>

          <div class="tab-pane fade" id="ingredients">
            <div class="tab-header text-center">
              <p>What Sharers</p>
              <h3>want to sell</h3>
            </div>

            <div class="row gy-5">
				<div class="row gy-5">
                {% for product in products_pack %}
				<div class="col-lg-4 sell-item">
					<a href="/product/{{product.id}}"><img src="/media/{{product.image }}" class="sell-img img-fluid" alt=""></a>
					<h4>{{product.title}}</h4>
					<p class="ingr">
						{{product.ingredients|slice:":40"}}
					</p>
					<p class="price">
						€{{product.price_per_quant}}
					</p>
				</div>

                {% endfor %}
			  </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>

{% endblock %}

website/templates/done.html
Thanks for your order!

Add map

website/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<section id="hero" class="hero d-flex align-items-center section-bg">
    <div class="container">
      <div class="row justify-content-between gy-5">
        <div class="col-lg-5 order-2 order-lg-1 d-flex flex-column justify-content-center align-items-center align-items-lg-start text-center text-lg-start">
          <h2 data-aos="fade-up">Don’t waste it<br>Share it</h2>
          <p data-aos="fade-up" data-aos-delay="100">Everyone can be a chef in their own kitchen. Have you cooked more? You bought more than you need? Don’t trow that away! Share with your Wolt community</p>
          <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
            <a href="/product/" class="btn-11">Start sharing now</a>
          </div>
        </div>
        <div class="col-lg-5 order-1 order-lg-2 text-center text-lg-start">
          <img src="{% static 'assets/img/hero-img.png' %}" class="img-fluid" alt="" data-aos="zoom-out" data-aos-delay="300">
        </div>
      </div>
    </div>
  </section>

  <main id="main">

    <section id="about" class="about">
    <div class="container" data-aos="fade-up">

      <div class="section-header">
        <h2>About Us</h2>
        <p>Learn More <span>About Us</span></p>
      </div>

      <div class="row gy-4">
        <div class="col-lg-7 position-relative about-img" style="background-image: url({%static 'assets/img/about.jpg'%}) ;" data-aos="fade-up" data-aos-delay="150">
          <div class="call-us position-absolute">
            <h4>If you want to know more:</h4>
            <p><a href="https://wolt.com/en/drive">Wolt Drive</a></p>
          </div>
        </div>
        <div class="col-lg-5 d-flex align-items-end" data-aos="fade-up" data-aos-delay="300">
          <div class="content ps-0 ps-lg-5">
            <p class="fst-italic">
              Wolt Share is a bridge between people to increase food waste management and help people to live healthy and sustainable life.
        We are delivering homemade food and ingredients from person to person.

            </p>
            <ul>
              <li><i class="bi bi-check2-all"></i> Delicious home-made food without spending a lot of money and time on cooking</li>
              <li><i class="bi bi-check2-all"></i> Cheaper ingredients</li>
              <li><i class="bi bi-check2-all"></i> Better life for our planet! </li>
            </ul>
            <p>
              Sharing is caring! Share, don’t waste!
            </p>

            <div class="position-relative mt-4">
              <img src="{%static 'assets/img/about-2.jpg'%}" class="img-fluid" alt="">
              <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
            </div>
          </div>
        </div>
      </div>


      </div>
    </section>
  </main>
{% endblock %}

website/templates/post_form.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

	<div class="container">
    <div class="row">
      <div class="col">
        Column
      </div>
      <div class="col">
        Column
      </div>
      <div class="col">
        Column
      </div>
    </div>
  </div>


    <main id="main">
        <section >
          <div class="container" data-aos="fade-up">
            <div class="section-header">
              <h2>Share your food</h2>
              <p>Upload <span>the food </span> you want to share</p>
            </div>

            <div class="row">
              <div class="col">



                <script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
                <div class="file-upload">
                  <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>

                  <div class="image-upload-wrap">
                    <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" />
                    <div class="drag-text">
                      <h3>Drag and drop here photos of your food</h3>
                    </div>
                  </div>
                  <div class="file-upload-content">
                    <img class="file-upload-image" src="#" alt="your image" />
                    <div class="image-title-wrap">
                      <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                    </div>
                  </div>
                </div>


                <div class="mt-3 ms-5 form-check">
                  <input type="checkbox" class="form-check-input" id="containter">
                  <label class="form-check-label" for="container">I will use my own container</label>
                </div>

                <div class="mt-3 ms-5 form-check">
                  <input type="checkbox" class="form-check-input" id="rules">
                  <label class="form-check-label" for="rules">I have read the <a href="">rules of responsibility</a> related to sharing food</label>
                </div>
              </div>
            <div class="col">
              <form>
                <div class="mb-4">
                  <label for="titleinput" class="form-label">Title</label>
                  <input type="text" class="form-control" id="title" aria-describedby="foodtitle">
                  <div id="foodtitle" class="form-text">Write a descriptive title for your food</div>
                </div>

                  <div class="row mb-4">
                  <div class="col-5">
                  <label for="titleinput" class="form-label">Select the food type</label>
                  <select class="form-control" id="foodtype">
                    <option>Cooked food</option>
                    <option>Packaged food</option>
                    <option>Fruits</option>
                    <option>Vegetables</option>
                  </select>
                  </div>

                  <div class="col-5">
                  <label for="titleinput" class="form-label">Select the food quantity</label>
                  <select class="form-control" id="foodtype">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                    </div>

                   <div class="col-2">
                  <label for="price" class="form-label">Price</label>
                  <input type="text" class="form-control" id="title" aria-describedby="foodtitle">
                </div>

                </div>


                <div class="mb-4">
                  <label for="descriptioninput" class="form-label">Briefly describe your food</label>
                   <textarea class="form-control" id="description" rows="3"></textarea>
                </div>

                <div class="mb-4">
                    <label for="allergens" class="form-label">Allergens:</label> <br>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredient1s" value="gluten">
                    <label class="form-check-label" for="ingredients1">Cereals</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredients2" value="Fish">
                    <label class="form-check-label" for="ingredients2">Fish</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredients3" value="Eggs">
                    <label class="form-check-label" for="ingredients3">Eggs</label>
                  </div>


                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredients4" value="Peanuts">
                    <label class="form-check-label" for="ingredients4">Peanuts</label>
                  </div>


                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredients5" value="Soybeans">
                    <label class="form-check-label" for="ingredients5">Soybeans</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="ingredients6" value="Milk">
                    <label class="form-check-label" for="ingredients6">Milk</label>
                  </div>
                </div>
              </form>
              </div>
              <button type="submit" class="btn btn-primary">PUBLISH</button>
            </div>
          </div>
        </section>

    </main>


{% endblock %}



{% comment %} {% load static %}
<html>

<link rel="stylesheet" href="{% static 'style.css' %}">

<body>

<form action="{% url 'woltshare:product_add' %}" method="post"> {% csrf_token %}
    Hello, Marco
    <br>

    <label for="quantity">Quantity</label>
    <input type="number" id="quantity" name="quantity" placeholder="How many portions do you have?" value=5>
    <br>

    <label for="price_per_quant">Price per quantity</label>
    <input type="number" id="price_per_quant" name="price_per_quant" placeholder="Price for one portion" value=1>
    <br>

    <label for="description">Description</label>
    <input type="text" id="description" name="description" placeholder="Describe the food..." value="so good">
    <br>

{{...models.FOOD_TYPE_CHOICES}}

    <label for="food_type">Food type</label>
    <select id="food_type" name="food_type">
        <option value="PACK">Packaged</option>
        <option value="INGR">Ingredient</option>
      </select>
    <br>

    <label for="packaging">Does it have packaging?</label>
    <input type="checkbox" id="packaging" name="packaging" checked>
    <br>

    <label for="image">Image</label>
    <input type="file" id="image" name="image">
    <br>

    <input type="submit" value="Swoosh" />
</form>

</body>
</html> {% endcomment %}

website/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% comment %}

Product:

<br/><br/>

{{product.id}}<br/>
{{product.seller}}<br/>
{{product.quantity}}<br/>
{{product.price_per_quant}}<br/>
{{product.description}}<br/>
{{product.food_type}}<br/>
{{product.packaging}}<br/>

<a href="/thanks-for-your-order/">
 {% endcomment %}

{% block content %}
  <main id="main">
	  <section class="mt-5 py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/media/{{product.image}}" alt="food" /></div>
                    <div class="col-md-6">
                        <div class="small mb-1">Cooked by: <a href="/accounts/profile/{{product.seller.id}}">{{product.seller.name}}</a><span class="text-secondary"> (Helsinki, 10km)</span></div>
                        <h1 class="display-5 fw-bolder">{{product.title}}</h1>
						<h5>Date: {{ product.date }}</h5>
						<h5>Available portions: {{ product.quantity }}</h5>
                        <div class="fs-5 mb-4">
                            <span>€{{product.price_per_quant}}</span>
                            <p style="color: gray; font-size: 17px;">Shipping fee: €{{ shipping_cost }}</p>
                        </div>


                        <p class="lead">{{product.description}}</p>
						<p class="h6 mb-4">Ingredients: {{product.ingredients}}</p>
                        <div class="d-flex">
                            <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />

                            <a href="/purchase/{{product.id}}">
                                <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                    <i class="bi-cart-fill me-1"></i>
                                    Buy
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

  </main>

{% endblock %}

website/templates/product_form.html
{% load static %}
<html>

<link rel="stylesheet" href="{% static 'style.css' %}">

<body>

<form method="post"> {% csrf_token %}
    Hello, Marco
    {{ form.as_p }}
    <input type="submit" value="Spaghetti">
</form>

</body>
</html>

website/templates/success.html
{% load static %}
<html>

<link rel="stylesheet" href="{% static 'style.css' %}">

<body>

    Hello, success, yay!
    <br>

    {{product}}

</body>
</html>

website/templates/user.html
User page